version: '2'
services:
  default:
    links:
      - mq-1:mq-1
      - mq-2:mq-2
  mq-1:
    image: rmohr/activemq:5.15.9-alpine
    ports:
      - 61620:61613
  mq-2:
    image: rmohr/activemq:5.15.9-alpine
    ports:
      - 61621:61613
